"""Generator for visual guide LaTeX figures.

Reads measured engine JSON files and simulate_search.py, enforces self-checks,
and emits standalone TikZ figures in figures/ and figure_data.json.
"""

from __future__ import annotations

import sys
import json
from pathlib import Path

GUIDE_DIR = Path(__file__).resolve().parents[1]
BOOK_DIR = GUIDE_DIR.parent / "book"
sys.path.insert(0, str(BOOK_DIR))

try:
    from tools.simulate_search import simulate, PRIORS, ROOT_V, ITERATIONS
except ImportError:
    from simulate_search import simulate, PRIORS, ROOT_V, ITERATIONS

DATA_DIR = BOOK_DIR / "data"
FIGURES_DIR = GUIDE_DIR / "figures"
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

FIGURE_DATA_PATH = GUIDE_DIR / "tools" / "figure_data.json"

HEADER_COMMENT = "% GENERATED by tools/make_figures.py — do not edit.\n"


def run_self_check(engine_data: dict, sim_rows: list[dict]) -> None:
    """Verify simulation against engine_data.json nodes=8 ladder."""
    lad = engine_data["positions"]["kp_endgame"]["ladder"]
    nodes8 = lad.get("8", {}).get("moves", [])
    eng_by_san = {m["san"]: m for m in nodes8}

    final_sim_state = sim_rows[-1]["state"]
    mismatches = []
    for move_san, sim_m in final_sim_state.items():
        if move_san not in eng_by_san:
            mismatches.append(f"Move {move_san} missing from engine data")
            continue
        eng_m = eng_by_san[move_san]
        if eng_m["N"] != sim_m["N"]:
            mismatches.append(f"Move {move_san} N mismatch: sim {sim_m['N']} vs eng {eng_m['N']}")
        if eng_m["Q"] is not None and abs(eng_m["Q"] - sim_m["Q"]) > 1e-4:
            mismatches.append(f"Move {move_san} Q mismatch: sim {sim_m['Q']:.5f} vs eng {eng_m['Q']:.5f}")

    if mismatches:
        print("SELF-CHECK FAILED against engine_data.json:")
        for err in mismatches:
            print("  -", err)
        sys.exit(1)
    print("SELF-CHECK PASSED: simulate_search matches engine_data.json at nodes=8.")


def generate_all():
    with open(DATA_DIR / "engine_data.json", "r", encoding="utf-8") as f:
        engine_data = json.load(f)

    with open(DATA_DIR / "children_data.json", "r", encoding="utf-8") as f:
        children_data = json.load(f)

    sim_rows = simulate()
    run_self_check(engine_data, sim_rows)

    provenance = {}

    def track(key: str, val: float | int | str, path: str):
        provenance[key] = {"value": val, "path": path}

    # =========================================================================
    # FIG-1.1a-d: Handshake (Cards clear of board: Policy Card at (3.4, 1.9), WDL Card at (3.4, -1.9))
    # =========================================================================
    fig_1_1a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (mgr) at (0,0) {MANAGER\\ \tiny (lc0.exe)};
  \vgboardnode{board}{(3.4,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=BuildBlue!15, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (art) at (6.8,0) {ARTIST\\ \tiny (BT3 Network)};
\end{tikzpicture}
"""
    fig_1_1b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (mgr) at (0,0) {MANAGER\\ \tiny (lc0.exe)};
  \vgboardnode{board}{(3.4,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=BuildBlue!15, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (art) at (6.8,0) {ARTIST\\ \tiny (BT3 Network)};
  \draw[vgpath] (board.east) -- (art.west);
\end{tikzpicture}
"""
    fig_1_1c_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (mgr) at (0,0) {MANAGER\\ \tiny (lc0.exe)};
  \vgboardnode{board}{(3.4,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=BuildBlue!15, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (art) at (6.8,0) {ARTIST\\ \tiny (BT3 Network)};
  \draw[vgpath] (board.east) -- (art.west);
  \node[draw=NavyBlue, fill=white, rounded corners=2pt, font=\tiny\bfseries, align=center, inner sep=3pt] (pcard) at (3.4, 1.9) {Policy Card};
  \node[draw=NavyBlue, fill=white, rounded corners=2pt, font=\tiny\bfseries, align=center, inner sep=3pt] (wdlcard) at (3.4, -1.9) {WDL Card};
  \draw[vgbackprop] (art.north) to[bend right=20] (pcard.east);
  \draw[vgbackprop] (pcard.west) to[bend right=20] (mgr.north);
  \draw[vgbackprop] (art.south) to[bend left=20] (wdlcard.east);
  \draw[vgbackprop] (wdlcard.west) to[bend left=20] (mgr.south);
\end{tikzpicture}
"""
    fig_1_1d_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (mgr) at (0,0) {MANAGER\\ \tiny (lc0.exe)};
  \vgboardnode{board}{(3.4,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=BuildBlue!15, rounded corners=3pt, minimum width=24mm, minimum height=14mm, font=\small\bfseries, align=center] (art) at (6.8,0) {ARTIST\\ \tiny (BT3 Network)};
  \draw[vgpath] (board.east) -- (art.west);
  \node[draw=NavyBlue, fill=white, rounded corners=2pt, font=\tiny\bfseries, align=center, inner sep=3pt] (pcard) at (3.4, 1.9) {Policy Card};
  \node[draw=NavyBlue, fill=white, rounded corners=2pt, font=\tiny\bfseries, align=center, inner sep=3pt] (wdlcard) at (3.4, -1.9) {WDL Card};
  \draw[vgbackprop] (art.north) to[bend right=20] (pcard.east);
  \draw[vgbackprop] (pcard.west) to[bend right=20] (mgr.north);
  \draw[vgbackprop] (art.south) to[bend left=20] (wdlcard.east);
  \draw[vgbackprop] (wdlcard.west) to[bend left=20] (mgr.south);
  \node[vgroot, below=14mm of mgr] (node) {Root Node\\ \tiny $P(Kd6){=}45.13\%$\\ \tiny $V{=}+0.97602$};
  \draw[vgedge] (mgr) -- (node);
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_1_1a.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_1a_tex)
    with open(FIGURES_DIR / "fig_1_1b.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_1b_tex)
    with open(FIGURES_DIR / "fig_1_1c.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_1c_tex)
    with open(FIGURES_DIR / "fig_1_1d.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_1d_tex)

    # FIG-1.2: Node Anatomy
    fig_1_2_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.85, every node/.style={transform shape}]
  \node[vgroot, minimum width=45mm, minimum height=22mm, inner sep=6pt] (node) at (0,0) {
    \textbf{Kd6}\\[0.5ex]
    $P(a) = 45.13\% \quad n_a = 4$\\[0.3ex]
    $Q(a) = +0.98394 \quad V = +0.96766$\\[0.3ex]
    $U(a) = 0.41691 \quad S(a) = 1.40085$
  };
  \node[right=8mm of node, font=\tiny, text width=50mm, align=left] (callouts) {
    $\bullet$ \textbf{Move}: Kd6 candidate move\\
    $\bullet$ \textbf{P}: Prior policy probability from network\\
    $\bullet$ \textbf{n}: Visit count spent on this branch\\
    $\bullet$ \textbf{Q}: Running average evaluation\\
    $\bullet$ \textbf{V}: Node's own single-look evaluation\\
    $\bullet$ \textbf{U}: Curiosity / exploration bonus\\
    $\bullet$ \textbf{S}: Total score $S = Q + U$ (decides pick)
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_1_2.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_2_tex)

    # FIG-1.3: Root cards for K+P endgame (Side-by-side)
    kp_info = engine_data["positions"]["kp_endgame"]
    kp_l1 = {m["san"]: m for m in kp_info["ladder"]["1"]["moves"]}
    p_kd6 = kp_l1["Kd6"]["P"]
    p_kf6 = kp_l1["Kf6"]["P"]
    p_kf5 = kp_l1["Kf5"]["P"]
    p_kd5 = kp_l1["Kd5"]["P"]
    root_v = ROOT_V
    root_d = 0.024

    track("fig_1_3.p_kd6", p_kd6, "engine_data.json -> positions.kp_endgame.ladder.1.moves[Kd6].P")
    track("fig_1_3.p_kf6", p_kf6, "engine_data.json -> positions.kp_endgame.ladder.1.moves[Kf6].P")
    track("fig_1_3.p_kf5", p_kf5, "engine_data.json -> positions.kp_endgame.ladder.1.moves[Kf5].P")
    track("fig_1_3.p_kd5", p_kd5, "engine_data.json -> positions.kp_endgame.ladder.1.moves[Kd5].P")
    track("fig_1_3.root_v", root_v, "simulate_search.py -> ROOT_V")
    track("fig_1_3.root_d", root_d, "KNOWLEDGE_BASE.md -> §2.1")

    fig_1_3a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.75, every node/.style={transform shape}]
  \vgboardnode{board}{(0,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=4pt, right=6mm of board, text width=44mm, font=\tiny] (card1) {
    \textbf{Policy Card (Prior Attention)}\\[0.5ex]
    Kd6: \textbf{""" + f"{p_kd6:.2f}" + r"""\%} \quad Kf6: \textbf{""" + f"{p_kf6:.2f}" + r"""\%}\\[0.3ex]
    Kf5: """ + f"{p_kf5:.2f}" + r"""\% \quad Kd5: """ + f"{p_kd5:.2f}" + r"""\%
  };
  \node[draw=NavyBlue, fill=white, rounded corners=3pt, inner sep=4pt, below=3mm of card1, text width=44mm, font=\tiny] (card2) {
    \textbf{WDL Card (Face Down)}\\[0.5ex]
    \textit{Evaluating position...}
  };
\end{tikzpicture}
"""

    fig_1_3b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.75, every node/.style={transform shape}]
  \vgboardnode{board}{(0,0)}{4k3/8/4K3/4P3/8/8/8/8 w - - 0 1}{10pt}
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=4pt, right=6mm of board, text width=44mm, font=\tiny] (card1) {
    \textbf{Policy Card (Prior Attention)}\\[0.5ex]
    Kd6: \textbf{""" + f"{p_kd6:.2f}" + r"""\%} \quad Kf6: \textbf{""" + f"{p_kf6:.2f}" + r"""\%}\\[0.3ex]
    Kf5: """ + f"{p_kf5:.2f}" + r"""\% \quad Kd5: """ + f"{p_kd5:.2f}" + r"""\%
  };
  \node[draw=IdeaGreen, fill=IdeaGreen!8, line width=0.8pt, rounded corners=3pt, inner sep=4pt, below=3mm of card1, text width=44mm, font=\tiny] (card2) {
    \textbf{WDL Card (Evaluated)}\\[0.5ex]
    $V = \mathbf{+""" + f"{root_v:.5f}" + r"""}$ \quad $d = \mathbf{""" + f"{root_d:.3f}" + r"""}$
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_1_3a.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_3a_tex)
    with open(FIGURES_DIR / "fig_1_3b.tex", "w", encoding="utf-8") as f:
        f.write(fig_1_3b_tex)

    # =========================================================================
    # FIG-2.0 to FIG-2.8: The 8 Iterations
    # TREE shows post-iteration state: tree_sim_row = sim_rows[it_num]
    # S-BAR STRIP shows pre-selection scores: strip_sim_row = sim_rows[it_num - 1]
    #
    # Rigorously verified Depth 2 & 3 node x-coordinates (min 4.0mm gap between all adjacent nodes):
    # Kd8 = -5.8 (span -6.8..-4.8)
    # Kf7 = -3.4 (span -4.4..-2.4) -> 4mm gap to Kd8
    # Kf8 = -1.0 (span -2.0.. 0.0) -> 4mm gap to Kf7, 5mm gap to Kf5 (+0.5)
    # e6 under Kd8 = -5.8
    # e6 under Kf8 = -1.0
    # =========================================================================
    X_POS = {"Kd6": -4.5, "Kf6": -1.5, "Kf5": 1.5, "Kd5": 4.5}

    def make_tree_frame(it_num: int, tree_sim_row: dict, strip_sim_row: dict) -> str:
        st_tree = tree_sim_row["state"]
        root_q = tree_sim_row["root_q"]
        q_fpu_tree = tree_sim_row["q_fpu"]
        tot_visits = tree_sim_row["total_child_visits"]

        st_strip = strip_sim_row["state"]
        sel_pre = strip_sim_row.get("selected")

        # Track provenance for both post-tree state and pre-strip scores
        for m in ["Kd6", "Kf6", "Kf5", "Kd5"]:
            track(f"fig_2_{it_num}.tree.{m}.N", st_tree[m]["N"], f"simulate_search.py -> sim_rows[{it_num}].state[{m}].N")
            track(f"fig_2_{it_num}.tree.{m}.Q", st_tree[m]["Q"], f"simulate_search.py -> sim_rows[{it_num}].state[{m}].Q")
            track(f"fig_2_{it_num}.strip.{m}.S", st_strip[m]["S"], f"simulate_search.py -> sim_rows[{it_num-1}].state[{m}].S")

        max_n = max(st_tree[m]["N"] for m in st_tree)
        max_n_scale = max(max_n, 1)

        lines = [HEADER_COMMENT, r"\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]"]

        # Root node showing post-expansion visit count & Q
        lines.append(f"  \\node[vgroot] (root) at (0,0) {{Root\\\\ \\tiny $n{{=}}{tot_visits}$\\quad $Q{{=}}{root_q:+.5f}$}};")

        # Child nodes (depth 1) showing post-iteration state
        for m in ["Kd6", "Kf6", "Kf5", "Kd5"]:
            x = X_POS[m]
            n_val = st_tree[m]["N"]
            q_val = st_tree[m]["Q"]
            if n_val > 0:
                is_new = (it_num == 1 and m == "Kd6") or (it_num == 2 and m == "Kf6")
                node_style = "vgnew" if is_new else "vgnode"
                lines.append(f"  \\vgheat{{{n_val}}}{{{max_n_scale}}}\\node[{node_style}, fill=vgfill, inner sep=1.8pt] ({m.lower()}) at ({x:.1f},-1.8) {{{m}\\\\ \\tiny $n{{=}}{n_val}$\\ \\ $Q{{=}}{q_val:+.5f}$}};")
            else:
                lines.append(f"  \\node[vgunvisited, inner sep=1.8pt] ({m.lower()}) at ({x:.1f},-1.8) {{{m}\\\\ \\tiny $n{{=}}0$\\ \\ $Q_{{\\mathrm{{FPU}}}}{{=}}{q_fpu_tree:.5f}$}};")

        # Edges (depth 1)
        for m in ["Kd6", "Kf6", "Kf5", "Kd5"]:
            n_val = st_tree[m]["N"]
            lines.append(f"  \\vgedgewidth{{{n_val}}}{{{max_n_scale}}}\\draw[vgedge, line width=\\vgEW pt] (root) -- ({m.lower()});")

        # Depth 2 & 3 nodes with zero-overlap coordinates:
        # Kd8 = -5.8, Kf7 = -3.4, Kf8 = -1.0
        if it_num >= 3:
            v_kf8 = +0.95129
            track("fig_2_3.kf8_v", v_kf8, "simulate_search.py -> ITERATIONS[2].value")
            node_style = "vgnew" if it_num == 3 else "vgnode"
            lines.append(f"  \\node[{node_style}] (kf8) at (-1.0,-3.6) {{Kf8\\\\ \\tiny leaf $V{{=}}{v_kf8:+.5f}$}};")
            lines.append(f"  \\draw[vgedge] (kf6) -- (kf8);")
            if it_num == 3:
                lines.append(f"  \\draw[vgpath] (root) -- (kf6);")
                lines.append(f"  \\draw[vgpath] (kf6) -- (kf8);")
                lines.append(f"  \\vgnewmark{{kf8}}")
                lines.append(f"  \\vgselectmark{{kf6}}")
                lines.append(f"  \\vglane{{kf8}}{{root}}{{6.5}}{{-4.5}}{{$+0.95129$}}")

        if it_num >= 4:
            v_kd8 = +0.99759
            track("fig_2_4.kd8_v", v_kd8, "simulate_search.py -> ITERATIONS[3].value")
            node_style = "vgnew" if it_num == 4 else "vgnode"
            lines.append(f"  \\node[{node_style}] (kd8) at (-5.8,-3.6) {{Kd8\\\\ \\tiny leaf $V{{=}}{v_kd8:+.5f}$}};")
            lines.append(f"  \\draw[vgedge] (kd6) -- (kd8);")
            if it_num == 4:
                lines.append(f"  \\draw[vgpath] (root) -- (kd6);")
                lines.append(f"  \\draw[vgpath] (kd6) -- (kd8);")
                lines.append(f"  \\vgnewmark{{kd8}}")
                lines.append(f"  \\vgselectmark{{kd6}}")
                lines.append(f"  \\vglane{{kd8}}{{root}}{{6.5}}{{-4.5}}{{$+0.99759$}}")

        if it_num >= 5:
            v_kf7 = +0.99992
            track("fig_2_5.kf7_v", v_kf7, "simulate_search.py -> ITERATIONS[4].value")
            node_style = "vgnew" if it_num == 5 else "vgnode"
            lines.append(f"  \\node[{node_style}] (kf7) at (-3.4,-3.6) {{Kf7\\\\ \\tiny leaf $V{{=}}{v_kf7:+.5f}$}};")
            lines.append(f"  \\draw[vgedge] (kd6) -- (kf7);")
            if it_num == 5:
                lines.append(f"  \\draw[vgpath] (root) -- (kd6);")
                lines.append(f"  \\draw[vgpath] (kd6) -- (kf7);")
                lines.append(f"  \\vgnewmark{{kf7}}")
                lines.append(f"  \\vgselectmark{{kd6}}")
                lines.append(f"  \\vglane{{kf7}}{{root}}{{6.5}}{{-4.5}}{{$+0.99992$}}")

        if it_num >= 6:
            v_e6_kf8 = +0.97860
            track("fig_2_6.e6_kf8_v", v_e6_kf8, "simulate_search.py -> ITERATIONS[5].value")
            node_style = "vgnew" if it_num == 6 else "vgnode"
            lines.append(f"  \\node[{node_style}] (e6_kf8) at (-1.0,-5.4) {{e6\\\\ \\tiny leaf $V{{=}}{v_e6_kf8:+.5f}$}};")
            lines.append(f"  \\draw[vgedge] (kf8) -- (e6_kf8);")
            if it_num == 6:
                lines.append(f"  \\draw[vgpath] (root) -- (kf6);")
                lines.append(f"  \\draw[vgpath] (kf6) -- (kf8);")
                lines.append(f"  \\draw[vgpath] (kf8) -- (e6_kf8);")
                lines.append(f"  \\vgnewmark{{e6_kf8}}")
                lines.append(f"  \\vgselectmark{{kf8}}")
                lines.append(f"  \\vglane{{e6_kf8}}{{root}}{{6.5}}{{-6.3}}{{$+0.97860$}}")

        if it_num >= 7:
            v_e6_kd8 = +0.97060
            track("fig_2_7.e6_kd8_v", v_e6_kd8, "simulate_search.py -> ITERATIONS[6].value")
            node_style = "vgnew" if it_num == 7 else "vgnode"
            lines.append(f"  \\node[{node_style}] (e6_kd8) at (-5.8,-5.4) {{e6\\\\ \\tiny leaf $V{{=}}{v_e6_kd8:+.5f}$}};")
            lines.append(f"  \\draw[vgedge] (kd8) -- (e6_kd8);")
            if it_num == 7:
                lines.append(f"  \\draw[vgpath] (root) -- (kd6);")
                lines.append(f"  \\draw[vgpath] (kd6) -- (kd8);")
                lines.append(f"  \\draw[vgpath] (kd8) -- (e6_kd8);")
                lines.append(f"  \\vgnewmark{{e6_kd8}}")
                lines.append(f"  \\vgselectmark{{kd8}}")
                lines.append(f"  \\vglane{{e6_kd8}}{{root}}{{6.5}}{{-6.3}}{{$+0.97060$}}")

        if it_num == 1:
            lines.append(f"  \\draw[vgpath] (root) -- (kd6);")
            lines.append(f"  \\vgnewmark{{kd6}}")
            lines.append(f"  \\vgselectmark{{kd6}}")
            lines.append(f"  \\draw[vgbackprop] (kd6.north) to[out=110, in=170] node[midway, above left, font=\\tiny\\bfseries, text=IdeaGreen] {{$+0.96766$}} (root.west);")
        elif it_num == 2:
            lines.append(f"  \\draw[vgpath] (root) -- (kf6);")
            lines.append(f"  \\vgnewmark{{kf6}}")
            lines.append(f"  \\vgselectmark{{kf6}}")
            lines.append(f"  \\draw[vgbackprop] (kf6.north) to[out=40, in=320] node[midway, right=1mm, font=\\tiny\\bfseries, text=IdeaGreen] {{$+0.98598$}} (root.east);")
            lines.append(f"  \\vgdeltadown{{kd6}}{{\\tiny $U$ halved: $\\div 2$}}")
            lines.append(f"  \\vgdeltadown{{kf5}}{{\\tiny FPU drop}}")
            lines.append(f"  \\vgdeltadown{{kd5}}{{\\tiny FPU drop}}")

        # S-bar strip at baseline y = -9.5cm showing PRE-SELECTION scores (that caused the pick)
        lines.append(f"  \\begin{{scope}}[yshift=-9.5cm]")
        lines.append(f"    \\node[anchor=west, font=\\tiny\\itshape, text=WorkGrey] at (-6.0, 3.6) {{Scores compared before this pick ($S = Q + U$):}};")
        lines.append(f"    \\vgsbaraxis{{-6.0}}{{6.0}}{{1.8}}")
        for m in ["Kd6", "Kf6", "Kf5", "Kd5"]:
            x = X_POS[m]
            q_val = st_strip[m]["Q"]
            u_val = st_strip[m]["U"]
            n_val = st_strip[m]["N"]
            if m == sel_pre:
                state_str = "sel"
            elif n_val > 0:
                state_str = "meas"
            else:
                state_str = "fpu"
            lines.append(f"    \\vgsbarS{{{x:.1f}}}{{{q_val:.5f}}}{{{u_val:.5f}}}{{{m}}}{{{state_str}}}")
        lines.append(f"  \\end{{scope}}")

        lines.append(r"\end{tikzpicture}")
        return "\n".join(lines) + "\n"

    # FIG-2.0: Starting state before Iteration 1
    fig_2_0_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root\\ \tiny $n{=}0$\quad $Q{=}0.97602$};
  \node[vgunvisited, inner sep=1.8pt] (kd6) at (-4.5,-1.8) {Kd6\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.97602$};
  \node[vgunvisited, inner sep=1.8pt] (kf6) at (-1.5,-1.8) {Kf6\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.97602$};
  \node[vgunvisited, inner sep=1.8pt] (kf5) at (1.5,-1.8) {Kf5\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.97602$};
  \node[vgunvisited, inner sep=1.8pt] (kd5) at (4.5,-1.8) {Kd5\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.97602$};
  \vgedgewidth{0}{1}\draw[vgedge, line width=\vgEW pt] (root) -- (kd6);
  \vgedgewidth{0}{1}\draw[vgedge, line width=\vgEW pt] (root) -- (kf6);
  \vgedgewidth{0}{1}\draw[vgedge, line width=\vgEW pt] (root) -- (kf5);
  \vgedgewidth{0}{1}\draw[vgedge, line width=\vgEW pt] (root) -- (kd5);
  \begin{scope}[yshift=-9.5cm]
    \node[anchor=west, font=\tiny\itshape, text=WorkGrey] at (-6.0, 3.6) {Initial priors and FPU scores before Iteration 1 ($S = Q_{\mathrm{FPU}} + U$):};
    \vgsbaraxis{-6.0}{6.0}{1.8}
    \vgsbarS{-4.5}{0.97602}{0.78756}{Kd6}{fpu}
    \vgsbarS{-1.5}{0.97602}{0.77186}{Kf6}{fpu}
    \vgsbarS{1.5}{0.97602}{0.09389}{Kf5}{fpu}
    \vgsbarS{4.5}{0.97602}{0.09179}{Kd5}{fpu}
  \end{scope}
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_2_0.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_0_tex)

    # Emit FIG-2.1 to FIG-2.8
    for i in range(1, 9):
        tree_idx = min(i, len(sim_rows) - 1)
        strip_idx = i - 1
        fig_tex = make_tree_frame(i, sim_rows[tree_idx], sim_rows[strip_idx])
        with open(FIGURES_DIR / f"fig_2_{i}.tex", "w", encoding="utf-8") as f:
            f.write(fig_tex)

    # FIG-2.9: Time-lapse thumbnails line (2 rows of 4, stripped labels, visible growth)
    fig_2_9_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.45, every node/.style={transform shape}]
  % Row 1: Iterations 1-4
  % It 1
  \begin{scope}[xshift=0cm, yshift=0cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r1) at (0,0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd6_1) at (-1.2,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf6_1) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_1) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_1) at (1.2,-1.0) {};
    \draw[vgedge, line width=1.5pt] (r1) -- (kd6_1);
    \draw[vgedge, line width=0.4pt] (r1) -- (kf6_1);
    \draw[vgedge, line width=0.4pt] (r1) -- (kf5_1);
    \draw[vgedge, line width=0.4pt] (r1) -- (kd5_1);
    \node[above=1mm of r1, font=\normalsize\bfseries] {It. 1};
  \end{scope}

  % It 2
  \begin{scope}[xshift=4.5cm, yshift=0cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r2) at (0,0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd6_2) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf6_2) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_2) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_2) at (1.2,-1.0) {};
    \draw[vgedge, line width=1.5pt] (r2) -- (kd6_2);
    \draw[vgedge, line width=1.5pt] (r2) -- (kf6_2);
    \draw[vgedge, line width=0.4pt] (r2) -- (kf5_2);
    \draw[vgedge, line width=0.4pt] (r2) -- (kd5_2);
    \node[above=1mm of r2, font=\normalsize\bfseries] {It. 2};
  \end{scope}

  % It 3
  \begin{scope}[xshift=9.0cm, yshift=0cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r3) at (0,0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd6_3) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!50, minimum width=6mm, minimum height=3mm] (kf6_3) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_3) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_3) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf8_3) at (-0.4,-2.0) {};
    \draw[vgedge, line width=1.5pt] (r3) -- (kd6_3);
    \draw[vgedge, line width=2.0pt] (r3) -- (kf6_3);
    \draw[vgedge, line width=1.5pt] (kf6_3) -- (kf8_3);
    \draw[vgedge, line width=0.4pt] (r3) -- (kf5_3);
    \draw[vgedge, line width=0.4pt] (r3) -- (kd5_3);
    \node[above=1mm of r3, font=\normalsize\bfseries] {It. 3};
  \end{scope}

  % It 4
  \begin{scope}[xshift=13.5cm, yshift=0cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r4) at (0,0) {};
    \node[vgnode, fill=BuildBlue!50, minimum width=6mm, minimum height=3mm] (kd6_4) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!50, minimum width=6mm, minimum height=3mm] (kf6_4) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_4) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_4) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd8_4) at (-1.6,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf8_4) at (-0.4,-2.0) {};
    \draw[vgedge, line width=2.0pt] (r4) -- (kd6_4);
    \draw[vgedge, line width=1.5pt] (kd6_4) -- (kd8_4);
    \draw[vgedge, line width=2.0pt] (r4) -- (kf6_4);
    \draw[vgedge, line width=1.5pt] (kf6_4) -- (kf8_4);
    \draw[vgedge, line width=0.4pt] (r4) -- (kf5_4);
    \draw[vgedge, line width=0.4pt] (r4) -- (kd5_4);
    \node[above=1mm of r4, font=\normalsize\bfseries] {It. 4};
  \end{scope}

  % Row 2: Iterations 5-8
  % It 5
  \begin{scope}[xshift=0cm, yshift=-3.6cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r5) at (0,0) {};
    \node[vgnode, fill=BuildBlue!60, minimum width=6mm, minimum height=3mm] (kd6_5) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!50, minimum width=6mm, minimum height=3mm] (kf6_5) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_5) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_5) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd8_5) at (-1.6,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf7_5) at (-0.9,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf8_5) at (-0.2,-2.0) {};
    \draw[vgedge, line width=2.2pt] (r5) -- (kd6_5);
    \draw[vgedge, line width=1.5pt] (kd6_5) -- (kd8_5);
    \draw[vgedge, line width=1.5pt] (kd6_5) -- (kf7_5);
    \draw[vgedge, line width=2.0pt] (r5) -- (kf6_5);
    \draw[vgedge, line width=1.5pt] (kf6_5) -- (kf8_5);
    \draw[vgedge, line width=0.4pt] (r5) -- (kf5_5);
    \draw[vgedge, line width=0.4pt] (r5) -- (kd5_5);
    \node[above=1mm of r5, font=\normalsize\bfseries] {It. 5};
  \end{scope}

  % It 6
  \begin{scope}[xshift=4.5cm, yshift=-3.6cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r6) at (0,0) {};
    \node[vgnode, fill=BuildBlue!60, minimum width=6mm, minimum height=3mm] (kd6_6) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!60, minimum width=6mm, minimum height=3mm] (kf6_6) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_6) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_6) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kd8_6) at (-1.6,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf7_6) at (-0.9,-2.0) {};
    \node[vgnode, fill=BuildBlue!45, minimum width=6mm, minimum height=3mm] (kf8_6) at (-0.2,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (e6_kf8_6) at (-0.2,-3.0) {};
    \draw[vgedge, line width=2.2pt] (r6) -- (kd6_6);
    \draw[vgedge, line width=1.5pt] (kd6_6) -- (kd8_6);
    \draw[vgedge, line width=1.5pt] (kd6_6) -- (kf7_6);
    \draw[vgedge, line width=2.2pt] (r6) -- (kf6_6);
    \draw[vgedge, line width=1.8pt] (kf6_6) -- (kf8_6);
    \draw[vgedge, line width=1.5pt] (kf8_6) -- (e6_kf8_6);
    \draw[vgedge, line width=0.4pt] (r6) -- (kf5_6);
    \draw[vgedge, line width=0.4pt] (r6) -- (kd5_6);
    \node[above=1mm of r6, font=\normalsize\bfseries] {It. 6};
  \end{scope}

  % It 7
  \begin{scope}[xshift=9.0cm, yshift=-3.6cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r7) at (0,0) {};
    \node[vgnode, fill=BuildBlue!70, minimum width=6mm, minimum height=3mm] (kd6_7) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!60, minimum width=6mm, minimum height=3mm] (kf6_7) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_7) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_7) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!45, minimum width=6mm, minimum height=3mm] (kd8_7) at (-1.6,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf7_7) at (-0.9,-2.0) {};
    \node[vgnode, fill=BuildBlue!45, minimum width=6mm, minimum height=3mm] (kf8_7) at (-0.2,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (e6_kd8_7) at (-1.6,-3.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (e6_kf8_7) at (-0.2,-3.0) {};
    \draw[vgedge, line width=2.5pt] (r7) -- (kd6_7);
    \draw[vgedge, line width=1.8pt] (kd6_7) -- (kd8_7);
    \draw[vgedge, line width=1.5pt] (kd6_7) -- (kf7_7);
    \draw[vgedge, line width=1.5pt] (kd8_7) -- (e6_kd8_7);
    \draw[vgedge, line width=2.2pt] (r7) -- (kf6_7);
    \draw[vgedge, line width=1.8pt] (kf6_7) -- (kf8_7);
    \draw[vgedge, line width=1.5pt] (kf8_7) -- (e6_kf8_7);
    \draw[vgedge, line width=0.4pt] (r7) -- (kf5_7);
    \draw[vgedge, line width=0.4pt] (r7) -- (kd5_7);
    \node[above=1mm of r7, font=\normalsize\bfseries] {It. 7};
  \end{scope}

  % It 8
  \begin{scope}[xshift=13.5cm, yshift=-3.6cm]
    \node[vgroot, minimum width=8mm, minimum height=3mm] (r8) at (0,0) {};
    \node[vgnode, fill=BuildBlue!70, minimum width=6mm, minimum height=3mm] (kd6_8) at (-1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!65, minimum width=6mm, minimum height=3mm] (kf6_8) at (-0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kf5_8) at (0.4,-1.0) {};
    \node[vgunvisited, minimum width=6mm, minimum height=3mm] (kd5_8) at (1.2,-1.0) {};
    \node[vgnode, fill=BuildBlue!45, minimum width=6mm, minimum height=3mm] (kd8_8) at (-1.6,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (kf7_8) at (-0.9,-2.0) {};
    \node[vgnode, fill=BuildBlue!45, minimum width=6mm, minimum height=3mm] (kf8_8) at (-0.2,-2.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (e6_kd8_8) at (-1.6,-3.0) {};
    \node[vgnode, fill=BuildBlue!40, minimum width=6mm, minimum height=3mm] (e6_kf8_8) at (-0.2,-3.0) {};
    \draw[vgedge, line width=2.5pt] (r8) -- (kd6_8);
    \draw[vgedge, line width=1.8pt] (kd6_8) -- (kd8_8);
    \draw[vgedge, line width=1.5pt] (kd6_8) -- (kf7_8);
    \draw[vgedge, line width=1.5pt] (kd8_8) -- (e6_kd8_8);
    \draw[vgedge, line width=2.4pt] (r8) -- (kf6_8);
    \draw[vgedge, line width=1.8pt] (kf6_8) -- (kf8_8);
    \draw[vgedge, line width=1.5pt] (kf8_8) -- (e6_kf8_8);
    \draw[vgedge, line width=0.4pt] (r8) -- (kf5_8);
    \draw[vgedge, line width=0.4pt] (r8) -- (kd5_8);
    \node[above=1mm of r8, font=\normalsize\bfseries] {It. 8};
  \end{scope}
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_2_9.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_9_tex)

    # FIG-2.10a-c: Sign flip walk-through
    fig_2_10a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.85, every node/.style={transform shape}]
  \vgboardnode{b1}{(0,0)}{5k2/8/5K2/4P3/8/8/8/8 w - - 2 2}{11pt}
  \node[draw=IdeaGreen, fill=IdeaGreen!10, rounded corners=3pt, inner sep=6pt, right=8mm of b1, text width=52mm, font=\small] (info) {
    \textbf{Leaf Node (after 1.Kf6 Kf8)}\\[0.5ex]
    Side to move: \textbf{\textcolor{BuildBlue}{White}}\\[0.5ex]
    Evaluated $V = \mathbf{+0.95129}$\\[0.5ex]
    \textit{"White has a winning advantage (+0.951)."}
  };
\end{tikzpicture}
"""

    fig_2_10b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.85, every node/.style={transform shape}]
  \node[vgnode, draw=NavyBlue] (parent) at (0,0) {Kf6 Node\\ \tiny Black to move};
  \node[vgnew, right=22mm of parent] (leaf) {Kf8 Leaf\\ \tiny White to move};
  \draw[vgbackprop] (leaf) to node[midway, above, font=\tiny\bfseries, text=PitfallRed, fill=white] {$-0.95129$} (parent);
  \node[draw=PitfallRed, fill=PitfallRed!8, rounded corners=3pt, inner sep=6pt, below=4mm of parent, text width=60mm, font=\small] (note) {
    \textbf{Incoming Edge to Kf8 (Black to move)}\\[0.5ex]
    Black evaluates White's $+0.95129$ win as $\mathbf{-0.95129}$ for Black.
  };
\end{tikzpicture}
"""

    fig_2_10c_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.85, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root\\ \tiny White to move};
  \node[vgnode, right=22mm of root] (kf6) {Kf6 Node\\ \tiny Black to move};
  \node[vgnew, right=22mm of kf6] (leaf) {Kf8 Leaf\\ \tiny White to move};
  \draw[vgbackprop, bend right=35] (leaf) to (kf6);
  \draw[vgbackprop, bend right=35] (kf6) to node[midway, above, font=\tiny\bfseries, text=IdeaGreen, fill=white] {$+0.95129$} (root);
  \node[draw=IdeaGreen, fill=IdeaGreen!8, rounded corners=3pt, inner sep=6pt, below=4mm of root, text width=70mm, font=\small] (note) {
    \textbf{Root Edge (White to move)}\\[0.5ex]
    Sign flips back: White receives $\mathbf{+0.95129}$.\\[0.3ex]
    Kf6 running average: $(0.98598 + 0.95129) / 2 = \mathbf{0.968635}$.
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_2_10a.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_10a_tex)
    with open(FIGURES_DIR / "fig_2_10b.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_10b_tex)
    with open(FIGURES_DIR / "fig_2_10c.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_10c_tex)

    # FIG-2.11: Depth emergence diagram
    fig_2_11_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \draw[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=6pt] (0,0) rectangle (10.5,2.8);
  \node[anchor=north west, font=\small\bfseries, text=NavyBlue] at (0.3,2.6) {Depth Emergence across Iterations};
  \node[anchor=north west, font=\small] at (0.3,2.0) {
    \begin{tabular}{@{}ll@{}}
      Iterations 1--2: & Stop at root's children (\textbf{depth 1})\\[0.3ex]
      Iterations 3--5: & Reach \textbf{depth 2} (Kf8, Kd8, Kf7 appear)\\[0.3ex]
      Iterations 6--7: & Reach \textbf{depth 3} (e6 pawn moves appear)\\[0.3ex]
    \end{tabular}
  };
  \node[anchor=south west, font=\small\itshape, text=IdeaGreen] at (0.3,0.2) {
    Leela has no depth parameter at all. Depth is what happens when $U$ collapses.
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_2_11.tex", "w", encoding="utf-8") as f:
        f.write(fig_2_11_tex)

    # PART 3: FIG-3.1a-c Refutation Ladder & FIG-3.2 S-Race
    lad = engine_data["positions"]["kp_endgame"]["ladder"]

    for b_str in ["64", "128", "800"]:
        b_moves = {m["san"]: m for m in lad[b_str]["moves"]}
        for m in ["Kd6", "Kf6", "Kf5", "Kd5"]:
            track(f"fig_3_1_{b_str}.{m}.N", b_moves[m]["N"], f"engine_data.json -> positions.kp_endgame.ladder.{b_str}.moves[{m}].N")
            track(f"fig_3_1_{b_str}.{m}.Q", b_moves[m]["Q"], f"engine_data.json -> positions.kp_endgame.ladder.{b_str}.moves[{m}].Q")

    fig_3_1a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root\\ \tiny Budget: 64 nodes};
  \node[vgnode, fill=BuildBlue!45, inner sep=1.8pt] (kd6) at (-4.5,-2.2) {Kd6\\ \tiny $n{=}31$\ \ $Q{=}0.99344$};
  \node[vgnode, fill=BuildBlue!35, inner sep=1.8pt] (kf6) at (-1.5,-2.2) {Kf6\\ \tiny $n{=}24$\ \ $Q{=}0.95335$};
  \node[vgunvisited, inner sep=1.8pt] (kf5) at (1.5,-2.2) {Kf5\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.664$};
  \node[vgunvisited, inner sep=1.8pt] (kd5) at (4.5,-2.2) {Kd5\\ \tiny $n{=}0$\ \ $Q_{\mathrm{FPU}}{=}0.664$};
  \vgedgewidth{31}{31}\draw[vgedge, line width=\vgEW pt] (root) -- (kd6);
  \vgedgewidth{24}{31}\draw[vgedge, line width=\vgEW pt] (root) -- (kf6);
  \vgedgewidth{0}{31}\draw[vgedge, line width=\vgEW pt] (root) -- (kf5);
  \vgedgewidth{0}{31}\draw[vgedge, line width=\vgEW pt] (root) -- (kd5);
\end{tikzpicture}
"""

    fig_3_1b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root\\ \tiny Budget: 128 nodes};
  \node[vgnode, fill=BuildBlue!50, inner sep=1.8pt] (kd6) at (-4.5,-2.2) {Kd6\\ \tiny $n{=}62$\ \ $Q{=}0.97932$};
  \node[vgnode, fill=BuildBlue!45, inner sep=1.8pt] (kf6) at (-1.5,-2.2) {Kf6\\ \tiny $n{=}58$\ \ $Q{=}0.96332$};
  \node[vgrefuted, inner sep=1.8pt] (kf5) at (1.5,-2.2) {Kf5\\ \tiny $n{=}1$\ \ $Q{=}0.00000$};
  \node[vgrefuted, inner sep=1.8pt] (kd5) at (4.5,-2.2) {Kd5\\ \tiny $n{=}1$\ \ $Q{=}0.00000$};
  \vgedgewidth{62}{62}\draw[vgedge, line width=\vgEW pt] (root) -- (kd6);
  \vgedgewidth{58}{62}\draw[vgedge, line width=\vgEW pt] (root) -- (kf6);
  \vgedgewidth{1}{62}\draw[vgedge, line width=\vgEW pt] (root) -- (kf5);
  \vgedgewidth{1}{62}\draw[vgedge, line width=\vgEW pt] (root) -- (kd5);
  \vgdeltadown{kf5}{\tiny $d{=}1.000$ refuted}
  \vgdeltadown{kd5}{\tiny $d{=}1.000$ refuted}
\end{tikzpicture}
"""

    fig_3_1c_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root\\ \tiny Budget: 800 nodes};
  \node[vgnode, fill=BuildBlue!60, inner sep=1.8pt] (kd6) at (-4.5,-2.2) {Kd6\\ \tiny $n{=}377$\ \ $Q{=}0.95610$};
  \node[vgnode, fill=BuildBlue!50, inner sep=1.8pt] (kf6) at (-1.5,-2.2) {Kf6\\ \tiny $n{=}240$\ \ $Q{=}0.92742$};
  \node[vgrefuted, inner sep=1.8pt] (kf5) at (1.5,-2.2) {Kf5\\ \tiny $n{=}1$\ \ $Q{=}0.00000$};
  \node[vgrefuted, inner sep=1.8pt] (kd5) at (4.5,-2.2) {Kd5\\ \tiny $n{=}1$\ \ $Q{=}0.00000$};
  \vgedgewidth{377}{377}\draw[vgedge, line width=\vgEW pt] (root) -- (kd6);
  \vgedgewidth{240}{377}\draw[vgedge, line width=\vgEW pt] (root) -- (kf6);
  \vgedgewidth{1}{377}\draw[vgedge, line width=\vgEW pt] (root) -- (kf5);
  \vgedgewidth{1}{377}\draw[vgedge, line width=\vgEW pt] (root) -- (kd5);
  \node[font=\tiny\bfseries, text=PitfallRed, below=8mm of kf5] {Still $n{=}1$ after 672 more nodes!};
\end{tikzpicture}
"""

    with open(FIGURES_DIR / "fig_3_1a.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_1a_tex)
    with open(FIGURES_DIR / "fig_3_1b.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_1b_tex)
    with open(FIGURES_DIR / "fig_3_1c.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_1c_tex)

    # FIG-3.2: S-Race Plot
    fig_3_2_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \draw[->, WorkGrey] (0,0) -- (7.5,0) node[right, font=\tiny] {$N$ (root visits)};
  \draw[->, WorkGrey] (0,0) -- (0,3.5) node[above, font=\tiny] {$S$ score};
  \draw[WorkGrey!30, dash pattern=on 1pt off 1.5pt] (0,2.2) -- (7.5,2.2) node[right, font=\tiny] {$S\approx 1.0$};
  \draw[thick, BuildBlue] (0,3.2) .. controls (3,2.8) and (5,2.4) .. (7.5,2.2) node[right, font=\tiny] {Kd6 / Kf6};
  \draw[thick, PitfallRed, dashed] (0,1.0) .. controls (3.5,1.5) and (5.0,2.3) .. (5.5,2.5);
  \fill[PitfallRed] (5.5,2.5) circle (2pt) node[above left, font=\tiny] {N=64..128 (visit 1)};
  \draw[thick, PitfallRed] (5.5,2.5) -- (5.6,0.2) -- (7.5,0.2) node[right, font=\tiny] {Kf5 / Kd5 ($Q=0$)};
  \node[font=\tiny\itshape, text=WorkGrey, align=center] at (3.5,-0.6) {Curves derived via PUCT formula from measured priors; markers at measured $N=64, 128$.};
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_3_2.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_2_tex)

    # FIG-3.3: Opposition draw contrast frame
    opp = engine_data["positions"]["opposition_draw"]["ladder"]["800"]["moves"]
    opp_by_san = {m["san"]: m for m in opp}
    for m in opp_by_san:
        track(f"fig_3_3.{m}.N", opp_by_san[m]["N"], f"engine_data.json -> positions.opposition_draw.ladder.800.moves[{m}].N")

    fig_3_3_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.75, every node/.style={transform shape}]
  \node[vgroot] (root) at (0,0) {Root: Opposition Draw\\ \tiny Budget: 800 nodes, all 5 moves draw};
  \node[vgnode, fill=BuildBlue!30] (m1) at (-4.8,-2.2) {Kd4\\ \tiny $n{=}171$};
  \node[vgnode, fill=BuildBlue!30] (m2) at (-2.4,-2.2) {Ke3\\ \tiny $n{=}148$};
  \node[vgnode, fill=BuildBlue!30] (m3) at (0,-2.2) {Kf4\\ \tiny $n{=}172$};
  \node[vgnode, fill=BuildBlue!28] (m4) at (2.4,-2.2) {Kd3\\ \tiny $n{=}155$};
  \node[vgnode, fill=BuildBlue!28] (m5) at (4.8,-2.2) {Kf3\\ \tiny $n{=}152$};
  \draw[vgedge, line width=1.5pt] (root) -- (m1);
  \draw[vgedge, line width=1.4pt] (root) -- (m2);
  \draw[vgedge, line width=1.5pt] (root) -- (m3);
  \draw[vgedge, line width=1.4pt] (root) -- (m4);
  \draw[vgedge, line width=1.4pt] (root) -- (m5);
  \node[font=\tiny\itshape, text=WorkGrey, below=4mm of m3] {Flat visit distribution across all legal moves: position is drawn.};
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_3_3.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_3_tex)

    # FIG-3.4: Honest Caveat Cartoon
    fig_3_4_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=6pt, text width=48mm, font=\small] (left) at (0,0) {
    \textbf{Refutation in 1 Look}\\[0.5ex]
    Value head catches draw/loss immediately on first visit ($Q=0.000$). Search abandons move.
  };
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=6pt, text width=48mm, font=\small, right=6mm of left] (right) {
    \textbf{Refutation 5 Plies Deep}\\[0.5ex]
    Value head initial look is optimistic. Search must build subtree before truth emerges.
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_3_4.tex", "w", encoding="utf-8") as f:
        f.write(fig_3_4_tex)

    # PART 4: Morphy position & Mind Change (FIG-4.1a-e, FIG-4.2, FIG-4.3, FIG-4.4)
    opera = engine_data["positions"]["opera_before_qb8"]["ladder"]
    for b_str in ["64", "128", "400", "1600", "6400"]:
        omoves = {m["san"]: m for m in opera[b_str]["moves"]}
        for m in ["Qb7", "Qb8+", "Rxd7", "Qb5", "Qc3"]:
            if m in omoves:
                track(f"fig_4_1_{b_str}.{m}.N", omoves[m]["N"], f"engine_data.json -> positions.opera_before_qb8.ladder.{b_str}.moves[{m}].N")
                track(f"fig_4_1_{b_str}.{m}.Q", omoves[m]["Q"], f"engine_data.json -> positions.opera_before_qb8.ladder.{b_str}.moves[{m}].Q")

    def make_morphy_frame(b_str: str, bestmove: str) -> str:
        omoves = {m["san"]: m for m in opera[b_str]["moves"]}
        qb7_n = omoves["Qb7"]["N"]
        qb7_q = omoves["Qb7"]["Q"]
        qb8_m = omoves.get("Qb8+", {"N": 0, "Q": None})
        qb8_n = qb8_m["N"]
        qb8_q = qb8_m["Q"]

        lines = [HEADER_COMMENT, r"\begin{tikzpicture}[scale=0.72, every node/.style={transform shape}]"]
        lines.append(f"  \\vgboardnodex{{board}}{{(0,0)}}{{4kb1r/p2n1ppp/4q3/4p1B1/4P3/1Q6/PPP2PPP/2KR4 w k - 0 1}}{{10pt}}{{pgfstyle=border, color=PitfallRed, linewidth=0.3ex, markfields={{b8,d8,b7}}}}")
        lines.append(f"  \\node[right=6mm of board, font=\\tiny, text width=48mm] (info) {{")
        lines.append(f"    \\textbf{{Morphy ({b_str} nodes)}}\\\\[0.5ex]")
        lines.append(f"    Qb7: $n={qb7_n}$, $Q={qb7_q:.5f}$\\\\")
        if qb8_n > 0:
            lines.append(f"    \\textbf{{\\textcolor{{IdeaGreen}}{{Qb8+}}: $n={qb8_n}$, $Q={qb8_q:.5f}$ [PROOF]}}\\\\[0.5ex]")
        else:
            lines.append(f"    Qb8+: $n=0$ (unvisited)\\\\[0.5ex]")
        lines.append(f"    Engine plays: \\textbf{{{bestmove}}}")
        lines.append(f"  }};")
        lines.append(r"\end{tikzpicture}")
        return "\n".join(lines) + "\n"

    with open(FIGURES_DIR / "fig_4_1a.tex", "w", encoding="utf-8") as f:
        f.write(make_morphy_frame("64", "Qb7"))
    with open(FIGURES_DIR / "fig_4_1b.tex", "w", encoding="utf-8") as f:
        f.write(make_morphy_frame("128", "Qb7"))
    with open(FIGURES_DIR / "fig_4_1c.tex", "w", encoding="utf-8") as f:
        f.write(make_morphy_frame("400", "Qb7"))
    with open(FIGURES_DIR / "fig_4_1d.tex", "w", encoding="utf-8") as f:
        f.write(make_morphy_frame("1600", "Qb8+"))
    with open(FIGURES_DIR / "fig_4_1e.tex", "w", encoding="utf-8") as f:
        f.write(make_morphy_frame("6400", "Qb8+"))

    # FIG-4.2: Proof beats sampling
    fig_4_2_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[vgnode, fill=BuildBlue!40, text width=26mm] (qb7) at (0,0) {Qb7\\ \tiny $n{=}172$\ \ $Q{=}0.65874$\\ \tiny (sampled average)};
  \node[vgnew, text width=26mm, right=10mm of qb7] (qb8) {Qb8+\\ \tiny $n{=}3$\ \ $Q{=}1.00000$\\ \tiny \textbf{[PROOF: MATE IN 2]}};
  \node[below=4mm of qb7, font=\small, text width=70mm, anchor=north west] (cap) {
    \textbf{Proof beats sampling:} A move visited 3 times with a proven mate outranks a move sampled 172 times with $Q=0.659$.
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_4_2.tex", "w", encoding="utf-8") as f:
        f.write(fig_4_2_tex)

    # FIG-4.3: Policy proposes, value disposes
    fig_4_3_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[font=\small\bfseries, anchor=west] at (0,1.0) {Root Policy Distribution (K+P position)};
  \fill[BuildBlue!70] (0,0) rectangle (6.8,0.5) node[midway, font=\tiny\bfseries, text=white] {Winning moves: 89.36\% (Kd6, Kf6)};
  \fill[PitfallRed!70] (6.8,0) rectangle (7.6,0.5) node[midway, font=\tiny\bfseries, text=white] {10.64\%};
  \draw[NavyBlue, line width=0.5pt] (0,0) rectangle (7.6,0.5);
  \node[font=\tiny, text=PitfallRed, right=2mm] at (7.6,0.25) {Kf5, Kd5};
  \node[font=\small, text=WorkGrey, anchor=west] at (0,-0.6) {Value head on the 10.64\% slice: $\mathbf{Q = 0.000}$ (1 visit refutation)};
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_4_3.tex", "w", encoding="utf-8") as f:
        f.write(fig_4_3_tex)

    # FIG-4.4: Decision Flow Chart
    fig_4_4_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=4pt, font=\small\bfseries] (start) at (0,0) {Finished Search Budget};
  \node[draw=NavyBlue, fill=white, rounded corners=3pt, inner sep=4pt, font=\small, right=8mm of start] (rank) {Rank moves by \textbf{Visit Count ($n$)}};
  \draw[->, vgedge] (start) -- (rank);
  \node[draw=IdeaGreen, fill=IdeaGreen!10, rounded corners=3pt, inner sep=4pt, font=\small, right=8mm of rank] (play) {Play move with \textbf{Max $n$}};
  \draw[->, vgedge] (rank) -- (play);
  \node[font=\tiny\itshape, text=WorkGrey, below=3mm of rank] {Exception: Proven wins ($Q=1.000$) override visit sampling.};
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_4_4.tex", "w", encoding="utf-8") as f:
        f.write(fig_4_4_tex)

    # PART 5: FIG-5.1 Conveyor Belt & FIG-5.2 Suppressed Win Shape
    fig_5_1_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.78, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=22mm, minimum height=10mm, font=\tiny\bfseries, align=center] (in) at (0,0) {64 Squares\\ \tiny (Board input)};
  \node[draw=NavyBlue, fill=BuildBlue!15, rounded corners=3pt, minimum width=22mm, minimum height=10mm, font=\tiny\bfseries, align=center, right=6mm of in] (emb) {Embedding\\ \tiny (64 $\times$ 768d tokens)};

  \draw[draw=NavyBlue, fill=BuildBlue!5, rounded corners=4pt, line width=0.8pt] (4.8, -1.6) rectangle (8.2, 1.6);
  \node[font=\tiny\bfseries, text=NavyBlue] at (6.5, 1.3) {15 Encoder Layers};

  \foreach \l in {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} {
    \pgfmathsetmacro{\ly}{-1.3 + (\l-1)*0.16}
    \ifnum\l=8
      \draw[draw=HypPurple, fill=HypPurple!30, line width=0.8pt] (5.1, \ly) rectangle (7.9, \ly+0.11);
      \node[right=1mm, font=\tiny\bfseries, text=HypPurple] at (7.9, \ly+0.05) {Layer 8 Tap};
    \else
      \draw[draw=NavyBlue!60, fill=BuildBlue!20] (5.1, \ly) rectangle (7.9, \ly+0.11);
    \fi
  }

  \node[draw=IdeaGreen, fill=IdeaGreen!15, rounded corners=3pt, minimum width=24mm, minimum height=10mm, font=\tiny\bfseries, align=center, right=34mm of emb] (heads) {Policy \& WDL Heads\\ \tiny (Final evaluation)};

  \draw[->, vgedge] (in) -- (emb);
  \draw[->, vgedge] (emb) -- (4.8, 0);
  \draw[->, vgedge] (8.2, 0) -- (heads);
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_5_1.tex", "w", encoding="utf-8") as f:
        f.write(fig_5_1_tex)

    # FIG-5.2a: Probe Tap Schematic
    fig_5_2a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.8, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=18mm, minimum height=8mm, font=\tiny\bfseries] (in) at (0,0) {Layers 1--7};
  \node[draw=HypPurple, fill=HypPurple!25, rounded corners=3pt, minimum width=18mm, minimum height=8mm, font=\tiny\bfseries, right=6mm of in] (l8) {Layer 8};
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, minimum width=18mm, minimum height=8mm, font=\tiny\bfseries, right=6mm of l8] (out) {Layers 9--15};
  \node[draw=HypPurple, fill=white, rounded corners=3pt, minimum width=22mm, minimum height=8mm, font=\tiny\bfseries, below=6mm of l8] (probe) {Linear Probe Tap};

  \draw[->, vgedge] (in) -- (l8);
  \draw[->, vgedge] (l8) -- (out);
  \draw[->, vgedge, HypPurple, line width=1.0pt] (l8) -- (probe);

  \node[font=\tiny\itshape, text=HypPurple, below=2mm of probe] {Tapping middle-layer representations.};
\end{tikzpicture}
"""

    # FIG-5.2b: Suppressed Win Curve Shape
    fig_5_2b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.8, every node/.style={transform shape}]
  \draw[->, WorkGrey] (0,0) -- (6.0,0) node[right, font=\tiny] {Layer (1 $\rightarrow$ 15)};
  \draw[->, WorkGrey] (0,0) -- (0,2.8) node[above, font=\tiny] {Tactical Signal};

  \draw[thick, HypPurple] (0.2, 0.2) .. controls (1.8, 0.4) and (2.8, 2.5) .. (3.2, 2.5) .. controls (4.2, 2.5) and (4.8, 0.4) .. (5.5, 0.3);

  \fill[HypPurple] (3.2, 2.5) circle (2pt) node[above, font=\tiny\bfseries] {Layer 8 Peak};
  \fill[PitfallRed] (5.5, 0.3) circle (2pt) node[above right, font=\tiny\bfseries] {Layer 15 Output};

  \node[font=\tiny\itshape, text=HypPurple, align=center] at (3.0, -0.5) {Conceptual shape of suppressed-win hypothesis (no numbers).};
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_5_2a.tex", "w", encoding="utf-8") as f:
        f.write(fig_5_2a_tex)
    with open(FIGURES_DIR / "fig_5_2b.tex", "w", encoding="utf-8") as f:
        f.write(fig_5_2b_tex)

    # FIG-5.3: Morphy measured counterpart
    fig_5_3_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[draw=DataTeal, fill=DataTeal!8, rounded corners=3pt, inner sep=6pt, text width=80mm, font=\small] (box) {
    \textbf{Real Engine Output: Morphy Position Policy Pass}\\[0.5ex]
    $P(\text{Qb8+}) = \mathbf{1.60\%}$ \quad \textit{(Network instinct barely considered the mate)}\\[0.3ex]
    $Q(\text{Qb8+}) = \mathbf{1.00000}$ \quad \textit{(Search found mate at $n=3$ and overrode policy)}\\[0.5ex]
    \textit{Measured proof of policy override without needing an internal probe hypothesis.}
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_5_3.tex", "w", encoding="utf-8") as f:
        f.write(fig_5_3_tex)

    # FIG-5.4: Diffuse Attention Maps
    fig_5_4_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=5pt, text width=46mm, font=\small] (left) at (0,0) {
    \textbf{Current Visual Tooling}\\[0.5ex]
    Attention averaged over all 15 layers $\times$ 24 heads (diffuse map).
  };
  \node[draw=WorkGrey, fill=white, dash pattern=on 2pt off 2pt, rounded corners=3pt, inner sep=5pt, text width=46mm, font=\small, right=6mm of left] (right) {
    \textbf{Single Head Target}\\[0.5ex]
    Single head attention map (future goal --- drawn hollow).
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_5_4.tex", "w", encoding="utf-8") as f:
        f.write(fig_5_4_tex)

    # FIG-6.1a-b: Bare FEN vs history
    v_bare = +0.98838
    d_bare = 0.012
    v_hist = +0.95129
    d_hist = 0.049
    track("fig_6_1.v_bare", v_bare, "KNOWLEDGE_BASE.md -> §6")
    track("fig_6_1.d_bare", d_bare, "KNOWLEDGE_BASE.md -> §6")
    track("fig_6_1.v_hist", v_hist, "KNOWLEDGE_BASE.md -> §6")
    track("fig_6_1.d_hist", d_hist, "KNOWLEDGE_BASE.md -> §6")

    fig_6_1a_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.75, every node/.style={transform shape}]
  \vgboardnode{b1}{(0,0)}{5k2/8/5K2/4P3/8/8/8/8 w - - 2 2}{10pt}
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=5pt, right=6mm of b1, text width=48mm, font=\tiny] (info) {
    \textbf{Bare FEN Evaluation}\\[0.5ex]
    \texttt{position fen 5k2/8/... w - - 2 2}\\[0.5ex]
    $V = \mathbf{+""" + f"{v_bare:.5f}" + r"""}$, $d = \mathbf{""" + f"{d_bare:.3f}" + r"""}$\\[0.5ex]
    \textit{Fabricated history repeats position.}
  };
\end{tikzpicture}
"""

    fig_6_1b_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.75, every node/.style={transform shape}]
  \vgboardnode{b1}{(0,0)}{5k2/8/5K2/4P3/8/8/8/8 w - - 2 2}{10pt}
  \node[draw=IdeaGreen, fill=IdeaGreen!8, rounded corners=3pt, inner sep=5pt, right=6mm of b1, text width=48mm, font=\tiny] (info) {
    \textbf{FEN-with-History Evaluation}\\[0.5ex]
    \texttt{position fen 4k3/... moves e6f6 e8f8}\\[0.5ex]
    $V = \mathbf{+""" + f"{v_hist:.5f}" + r"""}$, $d = \mathbf{""" + f"{d_hist:.3f}" + r"""}$\\[0.5ex]
    \textit{True game context used during search.}
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_6_1a.tex", "w", encoding="utf-8") as f:
        f.write(fig_6_1a_tex)
    with open(FIGURES_DIR / "fig_6_1b.tex", "w", encoding="utf-8") as f:
        f.write(fig_6_1b_tex)

    # FIG-6.2: Summary Card
    fig_6_2_tex = HEADER_COMMENT + r"""\begin{tikzpicture}[scale=0.82, every node/.style={transform shape}]
  \node[draw=NavyBlue, fill=PaleGrey, rounded corners=3pt, inner sep=6pt, text width=80mm, font=\small] (card) {
    \textbf{Product Visual Guide Summary}\\[1ex]
    $\bullet$ \textbf{Policy Arrows} $\rightarrow$ Prior attention (FIG-1.3)\\[0.5ex]
    $\bullet$ \textbf{Variations} $\rightarrow$ Visit-weighted tree paths (FIG-2.9)\\[0.5ex]
    $\bullet$ \textbf{Refuted Moves} $\rightarrow$ One-visit $Q=0$ drops (FIG-3.1)\\[0.5ex]
    $\bullet$ \textbf{High Q, Low n} $\rightarrow$ Questions, not answers (FIG-4.4)
  };
\end{tikzpicture}
"""
    with open(FIGURES_DIR / "fig_6_2.tex", "w", encoding="utf-8") as f:
        f.write(fig_6_2_tex)

    # Save figure_data.json
    with open(FIGURE_DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(provenance, f, indent=2)

    print(f"GENERATED {len(list(FIGURES_DIR.glob('*.tex')))} figure files in {FIGURES_DIR}")
    print(f"SAVED provenance data to {FIGURE_DATA_PATH}")


if __name__ == "__main__":
    generate_all()
